import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 20
